### ISSUE TITLE
Tilde sign

### ISSUE THREAD

**Issue by fhui28** [emitanaka/nestr#1]
I think I mentioned this before to you in private. With nesting, I like the use of an arrow structure more than a tilde sign to reflect the direction of what is nested in what. This might just be more of a personal preference though.

nest_in(1:3, # parental vector
        **1 <- 3**, # level 1 has 3 children
        **. <- 1**) # the remaining levels have 1 child

**Comment by emitanaka** [comment]
Nope for this sorry! Two sided formula is closer in syntax with `case_when`; arrow assignment within formula syntax can be misread, e.g. `1 < -3` is "one less than minus 3"; and it's actually a lot more work to implement what you want for very little benefit IMO.
